# .streamlit/secrets.toml

[tableau]
token_name = "wildlife"
token_secret = "sad3kNsSSAWpY5WmIVt+VA==:UtOLPMrNIEBu2Hak2y545zyyDodFNiSo"
server_url = "https://prod-apnortheast-a.online.tableau.com/"
site_id = "gauravsuryavanshidev6cb38334b3"  # in your site's URL behind the server_url
